### PR TITLE
fixed thrown error check

### PR DESCRIPTION
**Pull request by romanfromrome**
Because if there's no ``` 'find module' ``` in ```ex.message``` ,the ```-1``` value from ```indexOf``` is equal to ```true``` and you'll never know what hit you.

Right now basically on any error thrown in this ```try {} catch``` - you'll get ``` "Connection protocol not supported" ``` , which is wrong

Please review.

### CODE REVIEW

**Comment by dxg** [comment]
Good catch.
Could you also add a test to [orm-exports.js](https://github.com/dresende/node-orm2/blob/master/test/integration/orm-exports.js)?

**Comment by romanfromrome** [comment]
yes - sure :)

**Comment by romanfromrome** [comment]
@dxg , done. Please take a look.

**Comment by dxg** [comment]
I wish there were 48 hours in the day... sorry for the delay.

**Comment by dxg** [comment]
Published as part of v2.1.23

**Pull request merged**
