### PR TITLE
Has one with zero

### PR DESCRIPTION
**Pull request by stueynz**
I've got a pre-existing database that started all its 'serial' IDs at zero...so I need to allow for Zero as a valid value for FK column in hasOne().

hasValues() is only used in hasOne association, so it's probably ok to make this change.

### CODE REVIEW

**Comment by dxg** [comment]
Looks good and makes sense, however the new tests are failing in postgres :(

**Comment by stueynz** [comment]
Fixed for postgres....better check sqllite now.

**Comment by stueynz** [comment]
Fixed it for postgres & sqlite wonder what's wrong for redshift.

**Comment by stueynz** [comment]
Had to do a silly commit to force Travis to re-try the build.  Seems ok now.

**Comment by dxg** [comment]
:+1:

**Comment by dxg** [comment]
Released in [v2.1.29](https://www.npmjs.com/package/orm).

**Pull request merged**
